name: 'Auto Assign'
on: pull_request

jobs:
  add-reviews:
    runs-on: ubuntu-latest
    steps:
      - uses: kentaro-m/auto-assign-action@v1.1.2
        with:
          configuration-path: ".github/timewaster.yml"
  HTML-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2 # Requried will all actions
      - uses: Cyb3r-Jak3/html5validator-action@v0.4.4
        with:
          root: source/
